language: node_js
sudo: required
dist: trusty
node_js:
  - "4"
  - "6"
  - "7"
services: postgreqsl
before_script:
  - psql -c 'create database redidit;' -U postgres
  - psql -c 'create user redidit with login password 'redidit;' -U postgres
  - psql -c 'alter role redidit with superuser;' -U postgres

  deploy:
    skip_cleanup: true